apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: fastapi
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
      {{- with .Chart.Annotations }}
      annotations:
          {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - args:
            - bash
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: fastapi
          ports:
            - containerPort: 8000
          resources: {}
          command: ["python", "/srv/server.py"]
          imagePullPolicy: {{ .Values.image.pullPolicy  }}
      restartPolicy: Always
status: {}
