apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: fastapi
  labels:
    app: fastapi
spec:
  type: NodePort
  clusterIP: 10.99.83.33
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
      nodePort: 31312
  selector:
    app: fastapi
status:
  loadBalancer: {}
